### ISSUE TITLE
How do you use Lizzie?

### ISSUE THREAD

**Issue by mc-mong** [pasky/pachi#101]
How do you use Lizzie?

**Comment by lemonsqueeze** [comment]
Hi,

Maybe readme needs updating, i guess it's not so clear right now.
If you're on windows easiest is to use binary release from this [thread](https://github.com/featurecat/lizzie/issues/479):  
Start Lizzie and it should just work.

 [Lizzie-Pachi.0.6.beta.Windows.x64.CPU.zip](https://github.com/featurecat/lizzie/files/2775506/Lizzie-Pachi.0.6.beta.Windows.x64.CPU.zip) 

Otherwise:
- Download [Lizzie 0.6](https://github.com/featurecat/lizzie/releases/tag/0.6)
- Download [Pachi 12.30](https://github.com/pasky/pachi/releases/tag/pachi-12.30-jowa), extract in Lizzie folder
- Edit Lizzie config.txt [like so](https://github.com/pasky/pachi/#lizzie)

Optionally remove / rename leela-zero folder to make sure it's using Pachi and not Leela-Zero.

**Comment by lemonsqueeze** [comment]
Closing issue, README has been updated.
