### ISSUE TITLE
Linux release package is actually a zip file

### ISSUE THREAD

**Issue by EricFromCanada** [pasky/pachi#163]
While updating this package's Homebrew formula, it was noticed that the [latest Linux release file](https://github.com/pasky/pachi/releases/download/pachi-12.84/pachi-12.84-linux-static.tgz), although it claims to be a gzipped tarball as implied by the `.tgz` extension, it's [actually a zip file](https://github.com/Homebrew/homebrew-core/pull/155733#issuecomment-1830115591). Ideally it'd have the extension `.zip`. 
```
$ file pachi-12.84-linux-static.tgz 
pachi-12.84-linux-static.tgz: Zip archive data, at least v1.0 to extract
```

**Comment by lemonsqueeze** [comment]
Hi,
Thanks for pointing this, should be fixed now.

By the way Pachi really shouldn't be in homebrew anymore, it's been marked for removal a while ago ([PR123301](https://github.com/Homebrew/homebrew-core/pull/123301)).
I'm surprised the Pachi homebrew formula is still there, there's no way to get a decent build under homebrew since caffe has been deprecated. Do you know why it's still there ?

**Comment by EricFromCanada** [comment]
Probably because it'd need a pull request submitted to deprecate it. See the [docs regarding formula deprecation](https://docs.brew.sh/Deprecating-Disabling-and-Removing-Formulae) for guidance and [other examples in the repository](https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-core%20deprecate&type=code).

**Comment by lemonsqueeze** [comment]
I don't work for homebrew, it's not my job to do this.
You know the procedure, please take appropriate action to deprecate this formula,
I'll back it up if necessary.
